version: '3'

services:

  hassio:
    build: 
      context: ./
      args:
        BUILD_FROM: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20
    container_name: hassio_supervisor
    entrypoint: ["/bin/bash", "-c", "/start_hassio.sh"]
    # privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - HOMEASSISTANT_REPOSITORY=homeassistant/qemux86-64-homeassistant
      - SUPERVISOR_SHARE=${PWD}/data
      - SUPERVISOR_NAME=hassio_supervisor
      - SUPERVISOR_API=hassio_supervisor
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      # - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
