name: Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - { arch: aarch64, build_from: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20" }
          - { arch: armhf, build_from: "ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.20" }
          - { arch: armv7, build_from: "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20" }
          - { arch: amd64, build_from: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20" }
          - { arch: i386, build_from: "ghcr.io/home-assistant/i386-base-python:3.12-alpine3.20" }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --platform linux/${{ matrix.architecture.arch }} \
          --build-arg BUILD_FROM=${{ matrix.architecture.build_from }} \
          --tag ghcr.io/${{ github.repository }}:${{ matrix.architecture.arch }}-latest \
          --push .

